### ISSUE TITLE
No module named 'timm.scheduler.multistep_lr'

### ISSUE THREAD

**Issue by ZitengXue** [yyyujintang/VMRNN-PyTorch#1]
Thanks for your great work! But I got a issue about the timm, my version is 0.4.12, any solutions here?

**Comment by ZitengXue** [comment]
0.5.4 is ok

**Comment by yyyujintang** [comment]
Thanks for your interest in our work! timm==0.6.11 is OK. I fix the dependency, please refer to the latest readme file. Feel free to contact us if you have any questions.
